version: '3'

services: 
    project21-mongo:
        image: mongo
        container_name: project21-mongo
        hostname: project21-mongo
        restart: unless-stopped
        command: mongod
        ports:
            - "27017:27017"
            - "28017:28017"
        volumes: 
            - mongodbdata:/data/db
        networks: 
            - backend
    
    project21-backend:
        container_name: project21-backend
        hostname: project21-backend
        build: 
            context: ./
            dockerfile: Dockerfile
        environment: 
            MONGO_CONTAINER_NAME: 'project21-mongo'
            FRONTEND_CONTAINER_NAME: 'localhost'
            BACKEND_CONTAINER_NAME: 'localhost'
        ports: 
            - "8000:8000"
        volumes: 
            - ./Database:/Backend/Database
        networks: 
            - frontend
            - backend
        depends_on: 
            - project21-mongo
        links:
            - project21-mongo

    project21-frontend:
        container_name: project21-frontend
        hostname: project21-frontend
        build: 
            context: Frontend/
            dockerfile: Dockerfile
        environment: 
            REACT_APP_FRONTEND_CONTAINER_NAME: 'localhost'
            REACT_APP_BACKEND_CONTAINER_NAME: 'localhost:8000'
        tty: true
        ports: 
            - "3000:3000"
        networks: 
            - frontend
        depends_on: 
            - project21-backend
        links: 
            - project21-backend

networks: 
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes: 
    mongodbdata:
        driver: local